### ISSUE TITLE
Migrating to dropwizard 0.8+

### ISSUE THREAD

**Issue by amitjindal** [StanSvec/dropwizard-authorization#1]
Hi Stan,
I want to use this library. However it looks like the structure of classes has changed and this does not compiles. Is there a way you can help me fix this library (or if you have some spare cycles).

Thanks
Amit

**Comment by StanSvec** [comment]
Hi Amit,

I will start the migration to 0.8 version this week once I have more time. However I will probably change the approach to make it more flexible and this will require some effort. But I will keep the support for MVEL. JAX-RS 2.0 filters could be good way how to achieve this. Let me investigate on this.

**Comment by amitjindal** [comment]
Hey Thanks. I also feel your approach with MVEL is a good one. I saw this also: https://github.com/mathiasringhof/dropwizard-authrole but your approach allows using the familiar @Auth and allows applying complex role combinations.

Will wait for your upgrade.

**Comment by amitjindal** [comment]
Hi Stan, Did you get a chance to take a look at this?

**Comment by StanSvec** [comment]
Hi Amit, I am in the middle of that change. I need to solve many other things last days, but I think you may expect the first result soon. I am sorry for waiting.

**Comment by amitjindal** [comment]
Please don't say sorry. I just wanted to ask. I'll wait. Quite eager to use this code actually. As this is new I cannot do this myself else I would have.

**Comment by StanSvec** [comment]
Hi Amit, I was crazy busy last weeks so it took more time than I expected. You can try 0.1.1 testing version. Please see the readme file for the instructions. However it doesn't support MVEL expression authorization yet. I am going to release it as separated package ASAP.

**Comment by amitjindal** [comment]
Hi Stan,

I tried this but for some reason I am getting a host of errors that do not make sense to me.

```
! org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
! [[FATAL] No injection source found for a parameter of type public com.aquevix.bazinga.models.Page com.aquevix.bazinga.resources.PageResource.update(com.aquevix.auth.models.User,io.dropwizard.jersey.params.UUIDParam,com.aquevix.bazinga.models.Page,io.dropwizard.jersey.params.UUIDParam,io.dropwizard.jersey.params.UUIDParam) at index 0.; source='ResourceMethod{httpMethod=PUT, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.aquevix.bazinga.resources.PageResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@1c00d406]}, definitionMethod=public com.aquevix.bazinga.models.Page com.aquevix.bazinga.resources.PageResource.update(com.aquevix.auth.models.User,io.dropwizard.jersey.params.UUIDParam,com.aquevix.bazinga.models.Page,io.dropwizard.jersey.params.UUIDParam,io.dropwizard.jersey.params.UUIDParam),
```

This started happening after I added this:

```
        AuthorizationConfiguration authConfig = new AuthorizationConfiguration.Builder<User>()
                .setPolicy(ProtectionPolicy.PROTECT_ANNOTATED_ONLY)
                .addRole(new SecurityRole.USER())
                .addRole(new SecurityRole.ADMIN())
                .addRole(new SecurityRole.MANAGER())
                .addRole(new SecurityRole.SUPERADMIN())
                .setAuthentication(new JWTAuthFactory<>(new JWTAuthenticator(), "my-api", User.class, tokenVerifier, tokenParser))
                .build();
        environment.jersey().register(authConfig);  // <<=== THIS LINE CAUSES ERRORS.

```

Does this makes any sense to you?
Without this the application runs perfectly fine.

**Comment by StanSvec** [comment]
Hi Amit, that's unfortunate. Could you please share signature of method com.aquevix.bazinga.resources.PageResource.update(*) to see how this method and its parameters are annotated.

**Comment by StanSvec** [comment]
Also which Dropwizard version do you use pls?

**Comment by StanSvec** [comment]
Hi Amit, thank you for the reporting. I probably found the problem which may be related to your finding. You can see the failing test is here: https://github.com/StanSvec/dropwizard-authorization/blob/master/src/test/groovy/com/stansvec/dropwizard/auth/authorization/AuthorizationWithEntityTest.groovy

It looks like when @Auth annotation is used on the method level then injection resolver registered for this annotation is actually used for all method parameters causing the injection of custom entities failing. I afraid that only possible solution for this issue is to have two separated annotations: one for authentication / authorization and second one for principal instance injection. But let me double-check first. In that case I would probably use the same approach as planned for Dropwizard 0.9 and use SecurityContext for principal registration. That would unfortunately force the extension users to implement Java EE Principal interface for their principal objects.

Thanks again for cooperation. I haven't had an opportunity to use this extension in my own projects yet so it's good you already made some tests.

**Comment by StanSvec** [comment]
Hi Amit,

It should be fixed. If you need to inject principal instance into your resource methods please use @Principal annotation as described in the documentation. You can also already use Java EL expressions:  https://github.com/StanSvec/dropwizard-authorization-el.

**Comment by amitjindal** [comment]
Hey, Sorry I was out and could not reply sooner. Let me try this over the weekend.
I am currently using latest 0.8.x dropwizard.
Here's the signature:

```
    @PUT
    @Path("{id}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Timed 
    @UnitOfWork
    @ApiOperation("Update Single")
    public Page update(@Auth(required = true) User user, @PathParam("id") UUIDParam id, Page entity,
                       @NotNull @PathParam("prj") UUIDParam projectId,
                       @NotNull @PathParam("domain") UUIDParam domainId) {
```

**Comment by StanSvec** [comment]
This method should work even with the old 0.1.1 implementation. I don't know what could be wrong in that case.

What if you use dropwizard-authentication module only, i.e. use Dropwizard `@Auth` annotation on that User parameter and register corresponding `AuthFactory.binder(..)` in Jersey. Do you experience the same error or does this fix it?

When you try the new 0.1.4 version of the authorization module you need to change your method like this:

```
    @PUT
    @Path("{id}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Timed 
    @UnitOfWork
    @ApiOperation("Update Single")
    @Auth
    public Page update(@Principal User user, @PathParam("id") UUIDParam id, Page entity,
                       @NotNull @PathParam("prj") UUIDParam projectId,
                       @NotNull @PathParam("domain") UUIDParam domainId) {
```

If you have more methods like this in your resource class you can put @Auth annotation on class level.

But as I said I'm not convinced that the new version fix it. Please try and let me know.

**Comment by StanSvec** [comment]
The work is done. In case of any issue pls raise separate issue ticket.
